version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      SERVER_TYPE: 'WEB'
  bgio:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8001:8001'
    environment:
      SERVER_TYPE: 'BGIO'
